### ISSUE TITLE
Dark UI Status Bar

### ISSUE THREAD

**Issue by mattgraham** [atom/atom-dark-syntax#1]
Before: 
![](http://c.gr4m.com/image/1n42343s1L03/image)

Proposed: 
![](http://c.gr4m.com/image/0d0l2A0B3x2r/images)

I love the green sidebar showing whats modified/new however, in the light ui with the dark syntax the green gets lost. We can either make it wider or separate the border color and the green color a little more.

**Comment by kevinsawicki** [comment]
Closing this out, [One Dark](https://github.com/atom/one-dark-syntax) is the new default syntax and this theme is no longer actively worked on.
