### ISSUE TITLE
Improve text contrast

### ISSUE THREAD

**Issue by maxkfranz** [atom/atom-dark-syntax#14]
The text should be high in brightness (e.g. default text should be white/#fff)

This is a large usability concern. Without high contrast, text is much more difficult to read.

Comparison to Sublime:

Atom:
![screen shot 2015-04-15 at 10 43 10 am](https://cloud.githubusercontent.com/assets/989043/7161276/58cac8e8-e35c-11e4-89d5-074c2e166cbe.png)

Sublime:
![screen shot 2015-04-15 at 10 39 47 am](https://cloud.githubusercontent.com/assets/989043/7161281/5cf7f0d0-e35c-11e4-866e-030d64f1075a.png)

**Comment by simurai** [comment]
Not sure about this. The Atom dark theme has been in use like that for a year, I believe. So changing it now will probably not please everyone. Contrast is already quite high and for those that prefer even higher, could switch to another theme. Like Monokai, which looks like the Sublime screenshot is using.

**Comment by thomasjo** [comment]
I agree with @simurai. If you need/want higher contrast, switch to another syntax theme. As pointed out, [Monokai](https://atom.io/themes/monokai) is a good alternative.

**Comment by maxkfranz** [comment]
OK; thanks for the feedback!
