### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rugk** [atom/atom-dark-syntax#20]
[Enter steps to reproduce below:]

1. Click on a (orange) git-diff on the line number.

**Atom Version**: 1.0.15
**System**: Windows 7
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /D:/Users/%username%/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:81

TypeError: Cannot read property 'length' of undefined
  at LineDiffWorker.decorateDiffMarkers (D:\Users\%username%\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44:67)
  at HTMLDivElement.<anonymous> (D:\Users\%username%\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:34:14)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -3:08.1.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
  2x -3:03.3.0 settings-view:open (atom-pane.pane.active)
  3x -2:36.9.0 core:backspace (atom-text-editor#tree-view-background.opacity.editor.mini.is-focused)
     -1:52.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:44.9.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
     -0:57.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:55.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      [...]
    ]
  }
}
```

### Installed Packages

```coffee
# User
[...]
minimap, v4.13.3
[...]
minimap-git-diff, v4.1.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Is there any reason why you truncated the installed packages list?  Sometimes packages that may not seem related to the issue are actually the cause - in this case, `line-diff-details`.
It looks like the error has already been reported over at jakesankey/line-diff-details#7 - please follow that issue instead for updates.

**Comment by rugk** [comment]
> Is there any reason why you truncated the installed packages list?

Yes it was huge. :smiley: 

I didn't even knew any more that i had `line-diff-details` installed.

**Comment by rugk** [comment]
BTW if it's the wrong repo, why does Atom report I should create it here?

**Comment by 50Wliu** [comment]
Don't worry about how long the package list is :P.  As for why it got reported here instead of over at line-diff-details, the Notifications package still has a few bugs where it gets confused about where to report issues (see atom/notifications#66).

**Comment by rugk** [comment]
Ah okay, thanks for the explanation.
