### ISSUE TITLE
`@supports not` triggers incorrectly colored CSS

### ISSUE THREAD

**Issue by maxvoltar** [atom/atom-dark-syntax#28]
```
@supports not (-webkit-backdrop-filter: blur(10px)) {
  background: rgba(230, 230, 230, 1);
}
```

All CSS that comes after the first line loses its color coding. 

Screenshot:
![screenshot 2016-03-08 14 25 24](https://cloud.githubusercontent.com/assets/125779/13618557/9cda551e-e539-11e5-8b01-4187758bb054.png)

**Comment by 50Wliu** [comment]
@maxvoltar Sorry to crush your hopes, but this is still the wrong repo :grimacing:.  Can you please move it over to the [language-css](https://github.com/atom/language-css) repo?  Language packages handle tokenization of files, and then the syntax themes highlight files based on the tokenization.

**Comment by maxvoltar** [comment]
Goddammit, sorry!
