### ISSUE TITLE
Comments are grey on dark grey, not enough contrast

### ISSUE THREAD

**Issue by ghost** [atom/atom-dark-syntax#30]
Can we have the grey used for comments bumped up just a notch to provide better contrast?
![screenshot 2016-05-15 10 54 59](https://cloud.githubusercontent.com/assets/1934169/15274879/816a42e4-1a8b-11e6-9eff-34f74514cfd9.png)

**Comment by harrisnb** [comment]
Same issue for DOCTYPE in HTML files
![screen shot 2018-01-17 at 10 42 51](https://user-images.githubusercontent.com/8995108/35038622-3fe491ba-fb73-11e7-82d2-2de5f11ab611.png)
