### ISSUE TITLE
script tag highlighting

### ISSUE THREAD

**Issue by Kloranthy** [atom/atom-dark-syntax#34]
Atom Dark syntax theme with the One Dark UI theme
![broken_script_tags](https://cloud.githubusercontent.com/assets/11448054/21281850/199a5c1c-c3be-11e6-9074-f5599d154420.png)
Atom Dark syntax theme with the Atom Dark UI theme
![broken_script_tags_2](https://cloud.githubusercontent.com/assets/11448054/21281966/bba08770-c3be-11e6-8e9e-a5a79e199712.png)

I originally thought this issue was caused by combining the Atom Dark syntax theme with the One Dark UI theme, but I noticed the issue persists even when I switched to the Atom Dark UI theme.

OS: Fedora 25 64bit
Atom: 1.12.6
I haven't changed anything aside from font size. Let me know if there is any more information you need.

**Comment by simurai** [comment]
Yeah, this issue seems to be only with the Atom Dark Syntax theme. I can reproduce it too.

**Comment by 50Wliu** [comment]
This is actually a bug with language-html.
https://github.com/atom/language-html/issues/82

**Comment by simurai** [comment]
@50Wliu Should we still try to fix it in this theme? It should work by removing the `.syntax--source` from [this rule](https://github.com/atom/atom-dark-syntax/blob/master/styles/syntax.less#L123-L126). Like in the [One Syntax](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax/_base.less#L176-L192).

Might have other side effects, though.

**Comment by 50Wliu** [comment]
I mean we should ideally fix it in language-html, since the scopes are totally incorrect.  But if the CSS in this theme is also incorrect, then they should both be fixed!

**Comment by simurai** [comment]
> if the CSS in this theme is also incorrect

Hmm... good question. 🤔  I think `.syntax--source` is only used together with a language. Like `.syntax--source.syntax--js`. So not sure why `tag`s are scoped to a generic `source`. It got added from [the beginning](https://github.com/atom/atom-dark-syntax/commit/047172d59350580a437fa791bddd62a4f21cef49). Maybe it was just done to win in specificity. `¯\_(ツ)_/¯`
