### ISSUE TITLE
no syntax highlight in markdown files

### ISSUE THREAD

**Issue by encorechow** [atom/atom-dark-syntax#38]
Is there any ways to apply this theme in markdown files or this will happen in future versions? Thanks!

**Comment by 50Wliu** [comment]
This was fixed and will be out in the next 1.13.0 hotfix.

**Comment by steronydh** [comment]
This is not working in 0,28.0. Section headings beginning with # are highlighted, but \*\*bold\*\* and \*italic\* words are not.
