### ISSUE TITLE
Markdown not highlighting properly

### ISSUE THREAD

**Issue by steronydh** [atom/atom-dark-syntax#43]
Headers are highlighted but **\*\*bold\*\*** and *\*italic\** text is not.

Atom-dark-syntax 0.28.0 and Atom 1.18.0.

**Comment by k15a** [comment]
![screen shot 2017-06-23 at 11 07 01](https://user-images.githubusercontent.com/20357450/27475079-246d6b68-5804-11e7-8f23-106fdad6bd51.jpg)

This is working for me :)

**Comment by steronydh** [comment]
That's strange! It works for me with all the other built-in themes apart from atom-dark-syntax and atom-light-syntax.

**Comment by k15a** [comment]
Are you using the built-in `language-gfm` or a third party language plugin?

**Comment by steronydh** [comment]
The built-in one. It still happens if I disable all my plugins and restart.

![image](https://user-images.githubusercontent.com/4245329/27475503-5efffc52-57fd-11e7-97ec-250a9805c3a0.png)

**Comment by k15a** [comment]
Could you try to start Atom in safe mode?
```
atom --safe
```

**Comment by steronydh** [comment]
No change. I've just looked at the syntax.less file, and it looks like there aren't sections for .syntax--bold or .syntax--italic. Does it need them?

![image](https://user-images.githubusercontent.com/4245329/27476787-f2615488-5801-11e7-871b-0cf8423f2fb5.png)

**Comment by k15a** [comment]
Ahh sorry, I thought you're using the one-dark-syntax but you're actually using the old atom-dark-syntax. With atom-dark-syntax that's indeed not highlighted probably.

**Comment by steronydh** [comment]
No worries. :)
