### ISSUE TITLE
HTML tag name and tag attributes should have different colors

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom-dark-syntax#45]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Now in html file, the colors of tag name and tag attributes are the same, I suggest to make them different so that the code looks more beautiful.

### Steps to Reproduce

1. Open an html file

**Expected behavior:** tag names and tag attrs have different colors

**Actual behavior:** the colors are the same

**Reproduces how often:** 100%

### Versions

Atom    : 1.20.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ben3eeE** [comment]
They look different to me when using `one-dark-syntax`.

![image](https://user-images.githubusercontent.com/1058982/30053188-342bf4e4-9228-11e7-8317-4be521fff6eb.png)

**Comment by yubaoquan** [comment]
But we are talking about 
## atom-dark-syntax
not **one-dark-syntax**

**Comment by rsese** [comment]
Ahh right sorry about that - I just checked Atom Dark and it looks like your screenshot where the tag name is a light-blue and the the attribute is a light-purple.  So different colors but close.

Do you think the 2 colors don't contrast enough?

**Comment by yubaoquan** [comment]
It is not easy for user to distinct these two colors when their eyes are weak color-blindness.

**Comment by Ben3eeE** [comment]
@yubaoquan I am sorry for mixing up the repositories :blush:

**Comment by simurai** [comment]
Here a [PR](https://github.com/atom/atom-dark-syntax/pull/53) that changes attributes to a stronger magenta:

![image](https://user-images.githubusercontent.com/378023/33699128-8b2463b0-db54-11e7-97c5-f4e2edff7a50.png)
