### ISSUE TITLE
mysql syntax bug in php file

### ISSUE THREAD

**Issue by Cipa** [atom/atom-dark-syntax#5]
![screen shot 2014-08-13 at 2 36 07 pm](https://cloud.githubusercontent.com/assets/293377/3910560/dff88184-2318-11e4-8aa2-3b7aa4b65e39.png)

Thanks

**Comment by markie83** [comment]
comment gray out was not working in PHP after long SQL strings for me so I fixed it by setting PREFFERED LINE LENGTH to 2000 in the PHP GRAMMAR package settings

**Comment by simurai** [comment]
Not sure if this is still an issue, we can re-open if so.

Currently

```php
<?php
  $sql = 'SELECT modx_site_content.id,longtitle FROM modx_site_content JOIN modx_site_tmplvar_contentvalues ON contentid = modx_site_content.id WHERE template = 15 AND deleted = 0 AND published = 1 AND hidemenu = 0 AND modx_site_tmplvar_contentvalues.tmplvarid = 40 AND (modx_site_tmplvar_contentvalues.value LIKE "'.$parent.'||%" OR modx_site_tmplvar_contentvalues.value LIKE "%||'.$parent.'||%" OR modx_site_tmplvar_contentvalues.value LIKE "%||'.$parent.'" OR modx_site_tmplvar_contentvalues.value LIKE "'.$parent.'")';
?>
```

renders as:

![screen shot 2018-08-24 at 11 45 28 am](https://user-images.githubusercontent.com/378023/44562153-3ec61480-a793-11e8-8090-a9de87363c5c.png)
