### ISSUE TITLE
programm failure

### ISSUE THREAD

**Issue by factotum666** [atom/atom-dark-syntax#51]
I am trying to use Atom.  Clearly, despite having a degree in engineering math and physics, having been on the internet since 1994, and compuserve before that, and having 20 years writing code, include a bit of assembler, this system is beyond me.

All that I want to do is to write and edit simple text documents.   When I called up atom, I was given lots of choices.  The first, and so far only one that I opted to use was the one that enabled me  to choose a theme.   I elected the themes of atom light and atom dark (for text).   But when I clicked on the tab that said untitled, what I got was the (default) screen of grey on black.   And so far I have wasted 1/2 half hour trying to find out how to write simple text, with a simple black on white format as most of the universe does.

Also, the instructions here are way to verbose and involved for me to get past the first paragraph.
Thanks

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by simurai** [comment]
> I elected the themes of atom light and atom dark (for text).
> what I got was the (default) screen of grey on black
> trying to find out how to write simple text, with a simple black on white format

@factotum666 Sounds like you have a dark syntax theme, but would like one with a white background. You can change themes in the settings and choose Atom Light, for example:

![theme](https://user-images.githubusercontent.com/378023/44561295-0ae8f000-a78f-11e8-9658-763563628459.gif)
