### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Kein-project** [atom/atom-dark-syntax#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.23.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///F:/Atom/resources/app/static/index.html?loadSettings=%7B%22pathToOpen%22%3A%22F%3A%5C%5Cprojects%5C%5Ctretira-docs%22%2C%22bootstrapScript%22%3A%22f%3A%5C%5CAtom%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22f%3A%5C%5CAtom%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.165.0%22%2C%22initialPath%22%3A%22F%3A%5C%5Cprojects%5C%5Ctretira-docs%22%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at c:\Users\Kein\.atom\packages\terminal-status\lib\command-output-view.coffee:38:26
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:461:12)

```

### Commands

```
     -9:44.7 command-palette:toggle (input.hidden-input)
     -9:41.1 core:move-down (input.hidden-input)
     -9:40.8 core:move-up (input.hidden-input)
     -9:40.4 core:confirm (input.hidden-input)
     -9:40.4 git-log:show (input.hidden-input)
     -8:47.1 core:confirm (input.hidden-input)
     -8:39.9 core:delete (input.hidden-input)
     -8:38.5 core:save (input.hidden-input)
     -1:36.3 settings-view:install-packages (input.hidden-input)
     -1:26.5 core:confirm (input.hidden-input)
     -0:01.0 core:paste (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.2
autoclose-html, v0.13.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
color-picker, v1.2.6
docblockr, v0.5.8
file-icons, v1.4.4
git-log, v0.2.0
highlight-selected, v0.7.0
js-refactor, v0.3.0
jsformat, v0.7.18
jshint, v1.1.3
jslint, v0.10.2
language-ejs, v0.1.0
linter, v0.9.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-scss-lint, v0.0.11
markdown-format, v2.5.0
minimap, v3.5.3
monokai, v0.9.0
open-last-project, v0.1.1
pretty-json, v0.3.1
react, v0.7.8
refactor, v0.4.1
remember-session, v0.5.1
sassbeautify, v0.2.0
tabs-to-spaces, v0.8.0
terminal-status, v1.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
@benogle Any ideas why this package was targeted, and not terminal-status?

**Comment by benogle** [comment]
Looking into this now

**Comment by benogle** [comment]
After installing terminal status, I get this error immediately, and it reports the correct package. Seems to be fine in osx. See related issue at https://github.com/guileen/terminal-status/issues/40

Looking at windows...

**Comment by benogle** [comment]
On windows 8.1 the error is fine for me too. 

![screen shot 2015-01-07 at 11 31 13 am](https://cloud.githubusercontent.com/assets/69169/5651918/b70010b0-9660-11e4-98ee-bf31ac0a6f1f.png)

@Kein-project what version of windows are you on? When did this error happen for you? 

My hunch is that this line is messing up in some windows version: https://github.com/atom/notifications/blob/4c51cc871bf75075bd2fc667b219c9833b58cc78/lib/notification-element.coffee#L293

**Comment by benogle** [comment]
@Kein-project does it always report the error on this syntax package? I assume this happens on atom reload. Can you reload the editor a few times and check? 

If so are you willing to dig in a bit and place some log statements?

**Comment by izuzak** [comment]
Closing since the error should have been reported on a different package. :doughnut:
